import {
  IconBeaker, IconMolecule, IconDNA, IconShieldCheck, IconBuilding, IconGear,
  IconFlask, IconLayers, IconShield, IconArrowUp, IconRefresh, IconHeart,
  IconVenus, IconDroplet, IconLeaf, IconActivity, IconRun, IconClipboard,
  IconUtensils, IconHandshake, IconCard, IconCalendar, IconSearch, IconTestTube, IconSparkle,
  IconPos, IconBank, IconCash, IconWhatsApp, IconFileText, IconUser,
} from "./icons";

export const ICON_MAP = {
  beaker: IconBeaker,
  molecule: IconMolecule,
  dna: IconDNA,
  shieldcheck: IconShieldCheck,
  building: IconBuilding,
  gear: IconGear,
  flask: IconFlask,
  layers: IconLayers,
  shield: IconShield,
  arrowup: IconArrowUp,
  refresh: IconRefresh,
  heart: IconHeart,
  venus: IconVenus,
  droplet: IconDroplet,
  leaf: IconLeaf,
  activity: IconActivity,
  run: IconRun,
  clipboard: IconClipboard,
  utensils: IconUtensils,
  handshake: IconHandshake,
  card: IconCard,
  calendar: IconCalendar,
  search: IconSearch,
  testtube: IconTestTube,
  sparkle: IconSparkle,
  pos: IconPos,
  bank: IconBank,
  cash: IconCash,
  whatsapp: IconWhatsApp,
  filetext: IconFileText,
  user: IconUser,
};
